### ISSUE TITLE
Need to bump required version of `gitdb`

### ISSUE THREAD

**Issue by cfobel** [conda-forge/gitpython-feedstock#13]
As of [2ca7c019][0], [GitPython][1] requires [`gitdb>=2.0.0`][2].

However, the [current `gitpython-feedstock` build rules are too loose, requiring `gitdb >=0.6.4`][3].

[0]: https://github.com/gitpython-developers/GitPython/commit/2ca7c019a359c64a040e7f836d3b508d6a718e28
[1]: https://github.com/gitpython-developers/GitPython
[2]: https://github.com/gitpython-developers/GitPython/blob/552a0aa094f9fd22faf136cdbc4829a367399dfe/setup.py#L68
[3]: https://github.com/conda-forge/gitpython-feedstock/blob/625b47068b21d263f9cf5d43648150cb3d3bf150/recipe/meta.yaml#L23

**Comment by ocefpaf** [comment]
@cfobel would you be interested in submitting a PR to fix that? It seems that a new version of `gitdb` is needed first. ~~The confusing part is that PyPI still lists `gitdb 0.6.4` as the latest version.~~ Oh, I see `gitdb2` is another package. So we need to submit that to [staged-recipes](https://github.com/conda-forge/staged-recipes) first.

**Comment by cfobel** [comment]
Thanks for the response @ocefpaf .  I haven't authored any conda-forge recipes so am not familiar with the process.  I'll try to figure things out when I have some more time to look into it.

**Comment by ocefpaf** [comment]
Take a look at our [FAQ](https://github.com/conda-forge/staged-recipes#faq), [docs](http://conda-forge.github.io/docs/), and [example recipe](https://github.com/conda-forge/staged-recipes/blob/master/recipes/example/meta.yaml) to get you started. But feel free to bug me along the way.

**Comment by cfobel** [comment]
Thanks very much for the tips!
