### ISSUE TITLE
Update to 2.1.8

### ISSUE THREAD

**Issue by isuruf** [conda-forge/gitpython-feedstock#18]
2.1.8 has some fixes for newer versions of git.

**Comment by pelson** [comment]
Recent updates from @notestaff and @ngoldbaum. If either of you wanted to get in on the gitpython feedstock maintainers list, I'd be super chuffed. 😉

**Comment by ocefpaf** [comment]
@isuruf I guess this one fell down the cracks. Do you still need this version?
If so let me know and I can send a PR for it.

**Comment by isuruf** [comment]
No, 2.1.10 is good enough. We should try removing the pinning at https://github.com/conda-forge/staged-recipes/blob/master/.travis_scripts/create_feedstocks#L38

**Comment by ocefpaf** [comment]
> We should try removing the pinning at https://github.com/conda-forge/staged-recipes/blob/master/.travis_scripts/create_feedstocks#L38

:+1: but I'm away from the infrastructure lately so I'll leave that to you and others who are more familiar with it :wink:
