### ISSUE TITLE
Add `git` run requirement

### ISSUE THREAD

**Issue by diegoferigo** [conda-forge/gitpython-feedstock#80]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Is there any specific reason why `gitpython` does not have the `git` package as run requirement?

https://github.com/conda-forge/gitpython-feedstock/blob/7eafcb6a08ecfc216fbd0bd4319a88b66d2901db/recipe/meta.yaml#L21-L24

xref https://github.com/conda-forge/rod-feedstock/pull/8
xref https://github.com/conda-forge/robot_descriptions-feedstock/issues/10

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

**Comment by diegoferigo** [comment]
cc-ing some of the maintainers @jakirkham @ocefpaf

**Comment by ocefpaf** [comment]
> Is there any specific reason why `gitpython` does not have the `git` package as run requirement?

Git is not added as a dependency upstream, probably b/c PyPI can't ship it. While we can be more complete and add it, folks are used to "bring your own git" and we may end up forcing our version on them instead. I'm reluctant to add b/c adding conda-forge's git manually to an env is not too hard and not as intrusive as making it a mandatory dependency.

**Comment by diegoferigo** [comment]
> > Is there any specific reason why `gitpython` does not have the `git` package as run requirement?
> 
> Git is not added as a dependency upstream, probably b/c PyPI can't ship it. While we can be more complete and add it, folks are used to "bring your own git" and we may end up forcing our version on them instead. I'm reluctant to add b/c adding conda-forge's git manually to an env is not too hard and not as intrusive as making it a mandatory dependency.

The main reason why PyPI packages do not ship the `git` command is because adding binaries inside wheels is a mess. I believe that one of the main benefits of using `conda-forge` is that packages have access also to C++ libraries and binaries - including `git`.

If there is no use-case of `gitpython` without the `git` binary, why not adding a run dependency without any specified version? It should not break any system since the users -as you wrote- until now were required to install it manually, and would prevent obtaining new environments with missing dependencies, especially when `gitpython` is quite deep in the dependency graph (as in my use-case).

**Comment by jakirkham** [comment]
There are a number of cases (particularly with Windows) where using our `git` (or `m2-git` specifically on Windows) doesn't work the way users expect. In these cases it is better not to require `git` and let users supply their own

**Comment by diegoferigo** [comment]
> There are a number of cases (particularly with Windows) where using our `git` (or `m2-git` specifically on Windows) doesn't work the way users expect. In these cases it is better not to require `git` and let users supply their own

Ok I see. Out of curiosity, can you either quickly comment or cross-ref any specific surprise users had with the `git` binary included in conda-forge? I'm not a Windows user since too long, and despite my long experience with git, I'm not yet seeing possible sources of those problems.

**Comment by ocefpaf** [comment]
Conda's git is usually latest and, sometimes, people don't want that. In my case, for example, I do use it on my laptop (v2.45.1) but I keep the older system (v2.34.1) one in all my day-job computers instead to avoid rocking the boat.

**Comment by diegoferigo** [comment]
> Conda's git is usually latest and, sometimes, people don't want that. In my case, for example, I do use it on my laptop (v2.45.1) but I keep the older system (v2.34.1) one in all my day-job computers instead to avoid rocking the boat.

Ok I see that such configuration can be problematic when you have conda environments always active. When not strictly necessary, I like to have self-contained environments that include all binaries and libraries (including a rolling version of `git`).

Though, I understand that there could be cases in which a local configuration of git stored in the user's home (or also the credentials) could create surprises. Similarly, also installing a package that requires git and expecting the user to do it manually can result surprising, but the solution is quick.

This being said, since you're also the maintainers of the `git` package, I believe you already experience many of such pitfalls. If you prefer requiring user action in this case, I'm ok with that. Thanks for the discussion, closing.
